version: "3.8"

services:
 db:
   image: postgres:14.5
   ports:
     - "5432:5432"
   environment:
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_DB: ${DB_NAME}

 app:
   build: .
   env_file: .env
   container_name: app
   volumes:
     - .:/main
   ports:
     - "8000:8000"
   depends_on:
     - db
