version: "3.8"

services:
 db:
   image: postgres:14.5
   ports:
     - "5432:5432"
   environment:
     POSTGRES_USER: ${DB_USER}
     POSTGRES_PASSWORD: ${DB_PASSWORD}
     POSTGRES_DB: ${DB_NAME}
   healthcheck:
     test: [ "CMD-SHELL", "pg_isready" ]
     interval: 10s
     timeout: 5s
     retries: 5

 app:
   build:
     context: .
     dockerfile: .docker/Dockerfile
   env_file: .env
   container_name: app
   volumes:
     - ./app:/var/app
   ports:
     - "8000:8000"
   depends_on:
     db:
       condition: service_healthy
